// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hFXLbBWU_7pvNHvXOIPYNurUY4Ga17Q',
    appId: '1:1053613180461:web:3239ddc74033c5cd0d1aa4',
    messagingSenderId: '1053613180461',
    projectId: 'beyou3',
    authDomain: 'beyou3.firebaseapp.com',
    storageBucket: 'beyou3.firebasestorage.app',
    measurementId: 'G-WLPS40TF2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa9qKLteV3Yhn-JIppvYl3Sk_FDyYsy88',
    appId: '1:1053613180461:android:bb83a3c2d25c45380d1aa4',
    messagingSenderId: '1053613180461',
    projectId: 'beyou3',
    storageBucket: 'beyou3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMwgvL6W32v1TlU6I0K3VGBAezd7gz0OY',
    appId: '1:1053613180461:ios:f72bfa884fbd60500d1aa4',
    messagingSenderId: '1053613180461',
    projectId: 'beyou3',
    storageBucket: 'beyou3.firebasestorage.app',
    iosBundleId: 'tech.brmja.beyou3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMwgvL6W32v1TlU6I0K3VGBAezd7gz0OY',
    appId: '1:1053613180461:ios:1369ba9292a08caf0d1aa4',
    messagingSenderId: '1053613180461',
    projectId: 'beyou3',
    storageBucket: 'beyou3.firebasestorage.app',
    iosBundleId: 'tech.brmja.beyou3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3hFXLbBWU_7pvNHvXOIPYNurUY4Ga17Q',
    appId: '1:1053613180461:web:5d30573a5915bcf10d1aa4',
    messagingSenderId: '1053613180461',
    projectId: 'beyou3',
    authDomain: 'beyou3.firebaseapp.com',
    storageBucket: 'beyou3.firebasestorage.app',
    measurementId: 'G-GYKRXPHN0E',
  );
}
